# Блок 6. Погружение в Python и анализ данных
## Занятие 12. Финальный проект блока: DataAnalyzer

## Цель занятия

Сначала изучите SOLVED-ноутбук вместе с преподавателем. Затем выполните TODO-ноутбук самостоятельно.

Это итоговое занятие блока 6.

Студент собирает мини-проект **DataAnalyzer**, который показывает, что он умеет:

- загружать CSV-датасет;
- изучать структуру данных;
- очищать данные;
- использовать NumPy;
- использовать Pandas;
- группировать данные;
- строить графики;
- формировать аналитический отчёт;
- готовить проект к переносу в VS Code и GitHub.

---

## Главная идея проекта

Мы берём реальный датасет и строим полный цикл анализа:

```text
загрузка → исследование → очистка → статистика → группировка → визуализация → отчёт → GitHub
```

---

## Датасет проекта

Используем датасет California Housing:

```text
https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv
```

Это датасет по районам Калифорнии и стоимости жилья.

### Описание колонок на русском языке

| Колонка | Описание |
|---|---|
| longitude | долгота района |
| latitude | широта района |
| housing_median_age | медианный возраст домов |
| total_rooms | общее количество комнат |
| total_bedrooms | общее количество спален |
| population | население района |
| households | количество домохозяйств |
| median_income | медианный доход |
| median_house_value | медианная стоимость жилья |
| ocean_proximity | близость к океану |

---

## Связь с дипломом

Такой проект можно использовать как основу дипломной работы.

В дипломе студент может заменить датасет:

- на данные клиентов;
- на данные продаж;
- на данные тренировок;
- на данные питания;
- на финансовые данные;
- на данные недвижимости своего региона.

---

## GitHub

Рекомендуемая ветка:

```bash
git checkout main
git pull origin main
git checkout -b feature/block6-final-dataanalyzer

git add .
git commit -m "feat: add block6 final dataanalyzer project"
git push -u origin feature/block6-final-dataanalyzer
```

После проверки:

```bash
git checkout main
git pull origin main
git merge feature/block6-final-dataanalyzer
git push origin main
```

## Ячейка 1. TODO: импорт библиотек

### Алгоритм

1. Импортируйте `pandas`.
2. Импортируйте `numpy`.
3. Импортируйте `matplotlib.pyplot`.
4. Выведите версии библиотек.
5. Добавьте assert.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from notebooks.block6_lesson10_groupby_reports_todo import target_col

print("Библиотеки подключены")
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

assert pd is not None
assert np is not None
assert plt is not None

Библиотеки подключены
Pandas: 3.0.5
NumPy: 2.5.2

## Ячейка 2. TODO: функции проекта

### Алгоритм

1. Создайте функцию `load_dataset`.
2. Создайте функцию `describe_columns_ru`.
3. Создайте функцию `basic_info`.
4. Проверьте, что функции вызываемые.

In [12]:
def load_dataset(url):
    return pd.read_csv(url)


def describe_columns_ru(column_descriptions):
    for column, description in column_descriptions.items():
        print(column, "—", description)


def basic_info(dataframe):
    print("Размер таблицы:", dataframe.shape)
    print("Колонки:", dataframe.columns.tolist())
    print()
    dataframe.info()


assert callable(load_dataset)
assert callable(describe_columns_ru)
assert callable(basic_info)

NameError: name 'url' is not defined

## Ячейка 3. TODO: загрузка датасета

### Алгоритм

1. Создайте переменную `url`.
2. Загрузите данные через `load_dataset`.
3. Покажите первые строки.
4. Проверьте наличие `median_house_value`.

In [13]:
url = "https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv"

df = load_dataset(url)

display(df.head())

target_col = "median_house_value"
assert len(df) > 0
assert target_col in df.columns

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

## Ячейка 4. TODO: описание колонок и исследование

### Алгоритм

1. Создайте словарь `column_descriptions`.
2. Выведите русское описание колонок.
3. Вызовите `basic_info(df)`.
4. Проверьте ключевые колонки.

In [15]:
column_descriptions = {
    "longitude": "долгота района",
    "latitude": "широта района",
    "housing_median_age": "медианный возраст домов",
    "total_rooms": "общее количество комнат",
    "total_bedrooms": "общее количество спален",
    "population": "население района",
    "households": "количество домохозяйств",
    target_col: "медианный доход",
    "median_house_value": "медианная стоимость жилья",
    "ocean_proximity": "близость к океану"
}

describe_columns_ru(column_descriptions)

print()
basic_info(df)

assert target_col in df.columns
assert "ocean_proximity" in df.columns

longitude — долгота района
latitude — широта района
housing_median_age — медианный возраст домов
total_rooms — общее количество комнат
total_bedrooms — общее количество спален
population — население района
households — количество домохозяйств
median_house_value — медианная стоимость жилья
ocean_proximity — близость к океану

Размер таблицы: (20640, 10)
Колонки: ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value', 'ocean_proximity']

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.7 MB

## Ячейка 5. TODO: очистка данных

### Алгоритм

1. Посчитайте пропуски до очистки.
2. Заполните `total_bedrooms` медианой.
3. Удалите дубликаты.
4. Посчитайте пропуски после очистки.
5. Проверьте результат.

In [20]:
missing_before = df.isna().sum().sum()

df_clean = df.copy()

median_bedrooms = df_clean["total_bedrooms"].median()
df_clean["total_bedrooms"] = df_clean["total_bedrooms"].fillna(median_bedrooms)

# df_clean = df_clean.drop_duplicates()

missing_after = df_clean.isna().sum().sum()

print("Пропусков до очистки:", missing_before)
print("Пропусков после очистки:", missing_after)
print("Размер после очистки:", df_clean.shape)

assert missing_after == 0
assert len(df_clean) > 0

Пропусков до очистки: 207
Пропусков после очистки: 0
Размер после очистки: (20640, 10)

## Ячейка 6. TODO: NumPy-статистика

### Алгоритм

1. Возьмите колонку `median_house_value`.
2. Преобразуйте её в NumPy-массив.
3. Посчитайте min, max, mean, std.
4. Сохраните результат в словарь.

In [21]:
house_values = df_clean["median_house_value"].to_numpy()

numpy_stats = {
    "min": np.min(house_values),
    "max": np.max(house_values),
    "mean": np.mean(house_values),
    "std": np.std(house_values)
}

for key, value in numpy_stats.items():
    print(key, ":", value)

assert numpy_stats["max"] >= numpy_stats["min"]
assert numpy_stats["mean"] > 0

min : 14999.0
max : 500001.0
mean : 206855.81690891474
std : 115392.82040412253

## Ячейка 7. TODO: Pandas-статистика и группировка

### Алгоритм

1. Используйте `describe()`.
2. Сгруппируйте по `ocean_proximity`.
3. Посчитайте count, mean, min, max.
4. Отсортируйте по mean.

In [23]:
stats = df_clean.describe()

display(stats)

group_report = (
    df_clean.groupby("ocean_proximity")[target_col]
    .agg(["count", "mean", "min", "max"])
    .sort_values(by="mean", ascending=False)
)

display(group_report)

assert "mean" in group_report.columns
assert group_report.shape[0] > 0

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,536.838857,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,419.391878,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,297.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,643.250000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

                 count           mean       min       max
ocean_proximity
ISLAND               5  380440.000000  287500.0  450000.0
NEAR BAY          2290  259212.311790   22500.0  500001.0
NEAR OCEAN        2658  249433.977427   22500.0  500001.0
<1H OCEAN         9136  240084.285464   17500.0  500001.0
INLAND            6551  124805.392001   14999.0  500001.0

## Ячейка 8. TODO: визуализация

### Алгоритм

1. Постройте гистограмму стоимости жилья.
2. Постройте scatter plot дохода и стоимости жилья.
3. Постройте bar chart по группам.
4. Добавьте подписи и сетку.

In [8]:
plt.figure(figsize=(8, 5))
plt.hist(df_clean["median_house_value"], bins=30)
plt.title("Распределение стоимости жилья")
plt.xlabel("Стоимость жилья")
plt.ylabel("Количество районов")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 5))
plt.scatter(df_clean["median_income"], df_clean["median_house_value"], alpha=0.25)
plt.title("Зависимость стоимости жилья от дохода")
plt.xlabel("Медианный доход")
plt.ylabel("Стоимость жилья")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 5))
group_report["mean"].plot(kind="bar")
plt.title("Средняя стоимость жилья по близости к океану")
plt.xlabel("Близость к океану")
plt.ylabel("Средняя стоимость")
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

assert len(group_report) > 0

## Ячейка 9. TODO: класс DataAnalyzer

### Алгоритм

1. Создайте класс `DataAnalyzer`.
2. Добавьте `__init__`.
3. Добавьте метод `get_numeric_statistics`.
4. Добавьте метод `get_group_report`.
5. Создайте объект и проверьте методы.

In [24]:
class DataAnalyzer:
    def __init__(self, dataframe):
        self.dataframe = dataframe

    def get_numeric_statistics(self, column):
        values = self.dataframe[column].to_numpy()
        return {
            "min": np.min(values),
            "max": np.max(values),
            "mean": np.mean(values)
        }

    def get_group_report(self, group_column, value_column):
        report = (
            self.dataframe.groupby(group_column)[value_column]
            .agg(["count", "mean", "min", "max"])
            .sort_values(by="mean", ascending=False)
        )
        return report


analyzer = DataAnalyzer(df_clean)

class_stats = analyzer.get_numeric_statistics("median_house_value")
class_group_report = analyzer.get_group_report("ocean_proximity", "median_house_value")

print(class_stats)
display(class_group_report)

assert class_stats["max"] >= class_stats["min"]
assert class_group_report.shape[0] > 0

{'min': np.float64(14999.0), 'max': np.float64(500001.0), 'mean': np.float64(206855.81690891474)}

                 count           mean       min       max
ocean_proximity
ISLAND               5  380440.000000  287500.0  450000.0
NEAR BAY          2290  259212.311790   22500.0  500001.0
NEAR OCEAN        2658  249433.977427   22500.0  500001.0
<1H OCEAN         9136  240084.285464   17500.0  500001.0
INLAND            6551  124805.392001   14999.0  500001.0

## Ячейка 10. TODO: итоговый отчёт и GitHub

### Алгоритм

1. Найдите категорию с самой высокой средней ценой.
2. Создайте `project_report`.
3. Создайте 5 выводов.
4. Выведите GitHub-команды.
5. Добавьте проверки.

In [25]:
top_category = group_report["mean"].idxmax()

project_report = {
    "project": "DataAnalyzer",
    "rows": len(df_clean),
    "columns": df_clean.shape[1],
    "mean_house_value": float(df_clean["median_house_value"].mean()),
    "top_category_by_price": top_category
}

print("Итоговый отчёт проекта:")
for key, value in project_report.items():
    print(key, ":", value)

conclusions = [
    "Проект DataAnalyzer загружает реальные данные из CSV.",
    "Данные очищены от пропусков и готовы к анализу.",
    "NumPy используется для быстрой числовой статистики.",
    "Pandas используется для группировки и аналитических отчётов.",
    "Графики помогают объяснить результаты анализа."
]

print()
print("Выводы:")
for item in conclusions:
    print("-", item)

print()
print("GitHub:")
print("git add .")
print('git commit -m "feat: complete block6 final dataanalyzer project"')
print("git push -u origin feature/block6-final-dataanalyzer")

assert project_report["rows"] > 1000
assert len(conclusions) == 5

Итоговый отчёт проекта:
project : DataAnalyzer
rows : 20640
columns : 10
mean_house_value : 206855.81690891474
top_category_by_price : ISLAND

Выводы:
- Проект DataAnalyzer загружает реальные данные из CSV.
- Данные очищены от пропусков и готовы к анализу.
- NumPy используется для быстрой числовой статистики.
- Pandas используется для группировки и аналитических отчётов.
- Графики помогают объяснить результаты анализа.

GitHub:
git add .
git commit -m "feat: complete block6 final dataanalyzer project"
git push -u origin feature/block6-final-dataanalyzer

# Итог TODO-задания

Покажите преподавателю:

- функции проекта;
- загрузку данных;
- очистку;
- NumPy-статистику;
- Pandas-группировку;
- графики;
- класс DataAnalyzer;
- итоговый отчёт;
- GitHub-команды.